name: Snap Bot Schedule

on:
  schedule:
    - cron: '0 5 * * *' # يشتغل كل يوم الفجر
  workflow_dispatch: # زر التشغيل اليدوي

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Run Python Script
        env:
          SNAP_USER: ${{ secrets.SNAP_USER }}
          SNAP_PASS: ${{ secrets.SNAP_PASS }}
        run: python bot.py
